// src/seeds/seedSessoes.js
require('dotenv').config();
const mongoose = require('mongoose');
const Sessao = require('../models/Sessao'); // Ajuste o caminho se necessário

// URL do MongoDB do .env
const MONGO_URI = process.env.MONGO_URI;

// **SEUS DADOS BRUTOS, AGORA DEFINIDOS GLOBALMENTE NO ARQUIVO**
const dadosBrutos = [
    { tipoSessao: "Escala", mestreDirigente: "Mestre Lauro", data: "02/02/2022", participantes: "Não informado", quemExplanou: "Conselheira Irmã da Dona Ju", quemLeuDocumentos: "Irmão Adenilson", estoqueInicial: "Não informado", quantidadeCoada: "Não informado", retornoSessao: "Não informado", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "João Quadra", data: "19/02/2022", participantes: "Não informado", quemExplanou: "Irmão Pietro", quemLeuDocumentos: "Irmão Rafael Wagner", estoqueInicial: "Não informado", quantidadeCoada: "Não informado", retornoSessao: "Não informado", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "Mestre Davi", data: "16/04/2022", participantes: "Não informado", quemExplanou: "Não informado", quemLeuDocumentos: "Não informado", estoqueInicial: "Não informado", quantidadeCoada: "Não informado", retornoSessao: "Não informado", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala Anual", mestreDirigente: "Mestre Paulo Afonso", data: "21/04/2022", participantes: "Não informado", quemExplanou: "Irmão Eduardo Zardo", quemLeuDocumentos: "Conselheira Emma Degraf", estoqueInicial: "Não informado", quantidadeCoada: "Não informado", retornoSessao: "Não informado", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Quadro de Mestre", mestreDirigente: "Mestre Irlan", data: "06/05/2022", participantes: "6", quemExplanou: "Não informado", quemLeuDocumentos: "Não informado", estoqueInicial: "Não informado", quantidadeCoada: "Não informado", retornoSessao: "Não informado", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "Conselheira Jacque Degraf", data: "07/05/2022", participantes: "Não informado", quemExplanou: "Conselheira Anna Quadra", quemLeuDocumentos: "Irmã Mariana", estoqueInicial: "Não informado", quantidadeCoada: "Não informado", retornoSessao: "Não informado", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "Conselheira Flavia", data: "21/05/2022", participantes: "Não informado", quemExplanou: "Irmão Diego de Jezus", quemLeuDocumentos: "Irmão Pablo", estoqueInicial: "Não informado", quantidadeCoada: "Não informado", retornoSessao: "Não informado", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "Mestre Cristian", data: "18/06/2022", participantes: "Não informado", quemExplanou: "Não informado", quemLeuDocumentos: "Conselheira Anna Quadra", estoqueInicial: "Não informado", quantidadeCoada: "Não informado", retornoSessao: "Não informado", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala Anual", mestreDirigente: "Mestre Davi Degraf", data: "23/06/2022", participantes: "Não informado", quemExplanou: "Irmã Iona", quemLeuDocumentos: "Irmão Reinald", estoqueInicial: "Não informado", quantidadeCoada: "Não informado", retornoSessao: "Não informado", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "Conselheiro Rafael Wagner", data: "02/07/2022", participantes: "Não informado", quemExplanou: "Irmã Rafaela", quemLeuDocumentos: "Irmão João Pedro", estoqueInicial: "Não informado", quantidadeCoada: "Não informado", retornoSessao: "Não informado", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "Irmão Pietro", data: "16/07/2022", participantes: "Não informado", quemExplanou: "Não informado", quemLeuDocumentos: "Conselheiro Rafael Wagner", estoqueInicial: "Não informado", quantidadeCoada: "Não informado", retornoSessao: "Não informado", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala Anual", mestreDirigente: "Mestre Davi Degraf", data: "22/07/2022", participantes: "Não informado", quemExplanou: "Conselheira Marli Andrade", quemLeuDocumentos: "Irmão Vianei", estoqueInicial: "Não informado", quantidadeCoada: "Não informado", retornoSessao: "Não informado", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Casais", mestreDirigente: "Mestre Paulo de Tarso", data: "30/07/2022", participantes: "Não informado", quemExplanou: "Não informado", quemLeuDocumentos: "Não informado", estoqueInicial: "Não informado", quantidadeCoada: "Não informado", retornoSessao: "Não informado", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "Mestre Davi Degraf", data: "06/08/2022", participantes: "Não informado", quemExplanou: "Conselheiro Gilnei", quemLeuDocumentos: "Irmão Gustavo Gealh", estoqueInicial: "Não informado", quantidadeCoada: "Não informado", retornoSessao: "Não informado", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "Mestre João Quadra", data: "20/08/2022", participantes: "Não informado", quemExplanou: "Irmão Pietro Arnaud", quemLeuDocumentos: "Irmã Patricia de Jezus", estoqueInicial: "Não informado", quantidadeCoada: "Não informado", retornoSessao: "Não informado", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala Anual", mestreDirigente: "Mestre Davi Degraf", data: "01/11/2022", participantes: "Não informado", quemExplanou: "Irmão Reinald", quemLeuDocumentos: "Irmão Diego de Jezus", estoqueInicial: "Não informado", quantidadeCoada: "Não informado", retornoSessao: "Não informado", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "Mestre Saulo", data: "05/11/2022", participantes: "Não informado", quemExplanou: "Conselheira esposa do Mestre Cleiverton", quemLeuDocumentos: "Não informado", estoqueInicial: "Não informado", quantidadeCoada: "Não informado", retornoSessao: "Não informado", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "Mestre Irlan", data: "19/11/2022", participantes: "Não informado", quemExplanou: "Não informado", quemLeuDocumentos: "Não informado", estoqueInicial: "Não informado", quantidadeCoada: "Não informado", retornoSessao: "Não informado", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "Irmão Gustavo Gealh", data: "03/12/2022", participantes: "Não informado", quemExplanou: "Não informado", quemLeuDocumentos: "Não informado", estoqueInicial: "Não informado", quantidadeCoada: "Não informado", retornoSessao: "Não informado", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "Mestre Davi Degraf", data: "17/12/2022", participantes: "Não informado", quemExplanou: "Irmã Mariana", quemLeuDocumentos: "Irmã Valentina", estoqueInicial: "Não informado", quantidadeCoada: "Não informado", retornoSessao: "Não informado", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Instrutiva", mestreDirigente: "Mestre Cristian", data: "18/12/2022", participantes: "Não informado", quemExplanou: "Não informado", quemLeuDocumentos: "Não informado", estoqueInicial: "Não informado", quantidadeCoada: "Não informado", retornoSessao: "Não informado", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala Anual", mestreDirigente: "Mestre Dejair", data: "24/12/2022", participantes: "Não informado", quemExplanou: "Conselheiro Rafael Wagner", quemLeuDocumentos: "Irmão Diego de Jezus", estoqueInicial: "Não informado", quantidadeCoada: "Não informado", retornoSessao: "Não informado", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Extra", mestreDirigente: "Conselheiro Gilnei", data: "31/12/2022", participantes: "Não informado", quemExplanou: "Não informado", quemLeuDocumentos: "Não informado", estoqueInicial: "Não informado", quantidadeCoada: "Não informado", retornoSessao: "Não informado", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "Mestre João Bosco", data: "21/01/2023", participantes: "Não informado", quemExplanou: "Não informado", quemLeuDocumentos: "Não informado", estoqueInicial: "Não informado", quantidadeCoada: "Não informado", retornoSessao: "Não informado", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Extra", mestreDirigente: "Irmão Pablo Melek", data: "28/01/2023", participantes: "17", quemExplanou: "Não informado", quemLeuDocumentos: "Não informado", estoqueInicial: "Não informado", quantidadeCoada: "Não informado", retornoSessao: "Não informado", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala Anual", mestreDirigente: "Mestre Clayton", data: "10/02/2023", participantes: "Não informado", quemExplanou: "Samara Gomes", quemLeuDocumentos: "Davi Santos", estoqueInicial: "Não informado", quantidadeCoada: "Não informado", retornoSessao: "Não informado", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Direção", mestreDirigente: "Mestre Clayton", data: "11/02/2023", participantes: "11", quemExplanou: "Não informado", quemLeuDocumentos: "Não informado", estoqueInicial: "Não informado", quantidadeCoada: "Não informado", retornoSessao: "Não informado", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "Mestre Christyan Brenner", data: "04/03/2023", participantes: "Não informado", quemExplanou: "Conselheiro Gilnei", quemLeuDocumentos: "Irmão Enzo", estoqueInicial: "Não informado", quantidadeCoada: "Não informado", retornoSessao: "Não informado", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "Mestre Gabriel Condé", data: "17/06/2023", participantes: "Não informado", quemExplanou: "Não informado", quemLeuDocumentos: "Não informado", estoqueInicial: "Não informado", quantidadeCoada: "Não informado", retornoSessao: "Não informado", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala Anual", mestreDirigente: "Mestre Diego", data: "23/06/2023", participantes: "Não informado", quemExplanou: "Conselheiro Rafael", quemLeuDocumentos: "Irmão Reinald", estoqueInicial: "Não informado", quantidadeCoada: "Não informado", retornoSessao: "Não informado", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "Irmão Robert", data: "01/07/2023", participantes: "Não informado", quemExplanou: "Não informado", quemLeuDocumentos: "Não informado", estoqueInicial: "Não informado", quantidadeCoada: "Não informado", retornoSessao: "Não informado", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "Conselheira Kamila Riquelme", data: "15/07/2023", participantes: "Não informado", quemExplanou: "Mestre Christyan", quemLeuDocumentos: "Irmão Carlinhos", estoqueInicial: "Não informado", quantidadeCoada: "Não informado", retornoSessao: "Não informado", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala Anual", mestreDirigente: "Mestre Luciano", data: "22/07/2023", participantes: "Não informado", quemExplanou: "Irmão Pietro", quemLeuDocumentos: "Irmão Diego de Jezus", estoqueInicial: "Não informado", quantidadeCoada: "Não informado", retornoSessao: "Não informado", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Instrutiva", mestreDirigente: "Mestre Cesar Wilson", data: "23/07/2023", participantes: "28", quemExplanou: "Não informado", quemLeuDocumentos: "Não informado", estoqueInicial: "Não informado", quantidadeCoada: "Não informado", retornoSessao: "Não informado", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "Conselheiro Rafael Wagner", data: "02/12/2023", participantes: "40", quemExplanou: "Irmã Fabia Alessandra", quemLeuDocumentos: "Irmão Diego Portillo", estoqueInicial: "Não informado", quantidadeCoada: "6.600", retornoSessao: "4.400", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "C. Gustavo", data: "16/12/2023", participantes: "30", quemExplanou: "Reinald", quemLeuDocumentos: "Filipini", estoqueInicial: "Não informado", quantidadeCoada: "5.500", retornoSessao: "3.000", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Instrutiva", mestreDirigente: "M. Robert", data: "17/12/2023", participantes: "22", quemExplanou: "Sem", quemLeuDocumentos: "Sem", estoqueInicial: "Não informado", quantidadeCoada: "5.700", retornoSessao: "3.000", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala Anual", mestreDirigente: "Mestre Davi", data: "24/12/2023", participantes: "53", quemExplanou: "Não informado", quemLeuDocumentos: "Não informado", estoqueInicial: "Não informado", quantidadeCoada: "5.300", retornoSessao: "3.300", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Extra", mestreDirigente: "C.Rafael", data: "31/12/2023", participantes: "19", quemExplanou: "Não informado", quemLeuDocumentos: "Não informado", estoqueInicial: "Não informado", quantidadeCoada: "3.000", retornoSessao: "1.700", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala Anual", mestreDirigente: "Davi Degraf", data: "06/01/2024", participantes: "48", quemExplanou: "Eduardo Zardo", quemLeuDocumentos: "Diego de Jezus", estoqueInicial: "Não informado", quantidadeCoada: "6.500", retornoSessao: "5.700", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "BARTOLOMEU", data: "20/01/2024", participantes: "35", quemExplanou: "Heloisa", quemLeuDocumentos: "Ioná", estoqueInicial: "Não informado", quantidadeCoada: "5.200", retornoSessao: "3.300", estoqueFinal: "1.900", visitantes: "Não informado" },
    { tipoSessao: "Adventicio", mestreDirigente: "Davi Degraf", data: "21/01/2024", participantes: "45", quemExplanou: "Eduardo Zardo", quemLeuDocumentos: "Reinald Mendes", estoqueInicial: "Não informado", quantidadeCoada: "7.300", retornoSessao: "5.200", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "bartolomeu", data: "03/02/2024", participantes: "57", quemExplanou: "Aujor", quemLeuDocumentos: "Pablo", estoqueInicial: "Não informado", quantidadeCoada: "7.3", retornoSessao: "4.7", estoqueFinal: "2.6", visitantes: "Não informado" },
    { tipoSessao: "Extra", mestreDirigente: "Irmão Reinald Mendes", data: "13/02/2024", participantes: "7", quemExplanou: "Não informado", quemLeuDocumentos: "Não informado", estoqueInicial: "Não informado", quantidadeCoada: "1.900", retornoSessao: "0.650", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "Conselheiro Pietro", data: "17/02/2024", participantes: "41", quemExplanou: "Ioná", quemLeuDocumentos: "Pablo", estoqueInicial: "Não informado", quantidadeCoada: "4.1", retornoSessao: "3.5", estoqueFinal: "0.6", visitantes: "Não informado" },
    { tipoSessao: "Escala Anual", mestreDirigente: "Mestre Djair", data: "27/03/2024", participantes: "46", quemExplanou: "Conselheiro Pietro", quemLeuDocumentos: "Irmão João Pedro", estoqueInicial: "Não informado", quantidadeCoada: "8.000", retornoSessao: "6.500", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "Mestre Davi", data: "06/04/2024", participantes: "Não informado", quemExplanou: "Irmão Pedro", quemLeuDocumentos: "Irmão Diego", estoqueInicial: "Não informado", quantidadeCoada: "6800", retornoSessao: "5500", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Instrutiva", mestreDirigente: "Bartolomeu", data: "07/04/2024", participantes: "Não informado", quemExplanou: "Não informado", quemLeuDocumentos: "Não informado", estoqueInicial: "Não informado", quantidadeCoada: "4600", retornoSessao: "2600", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Sessão de Casal", mestreDirigente: "Mestre Cássio", data: "13/04/2024", participantes: "14", quemExplanou: "Não informado", quemLeuDocumentos: "Não informado", estoqueInicial: "Não informado", quantidadeCoada: "3.5", retornoSessao: "2.5", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "Mestre João da Cruz", data: "21/04/2024", participantes: "125", quemExplanou: "Mestre Dejair", quemLeuDocumentos: "Pietro", estoqueInicial: "Não informado", quantidadeCoada: "15.000", retornoSessao: "10.4", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Extra", mestreDirigente: "Mestre João da Cruz", data: "25/04/2024", participantes: "29", quemExplanou: "Não informado", quemLeuDocumentos: "Não informado", estoqueInicial: "Não informado", quantidadeCoada: "4.5", retornoSessao: "3.3", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "Irmã Mariana", data: "04/05/2024", participantes: "Não informado", quemExplanou: "Irmã Neuza", quemLeuDocumentos: "Irmã Carol", estoqueInicial: "52", quantidadeCoada: "6", retornoSessao: "3.4", estoqueFinal: "54.6", visitantes: "Não informado" },
    { tipoSessao: "Extra", mestreDirigente: "Conselheira Helicassia", data: "12/05/2024", participantes: "Não informado", quemExplanou: "Não informado", quemLeuDocumentos: "Não informado", estoqueInicial: "Não informado", quantidadeCoada: "3300", retornoSessao: "3000", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Adventícios", mestreDirigente: "Mestre Cassio", data: "11/05/2024", participantes: "Não informado", quemExplanou: "Cássio Junior", quemLeuDocumentos: "Eduarda Cassio", estoqueInicial: "Não informado", quantidadeCoada: "3300", retornoSessao: "3000", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "Mestre Darcione", data: "18/05/2024", participantes: "56", quemExplanou: "CCD Gilnei", quemLeuDocumentos: "Irmão Guilherme", estoqueInicial: "41", quantidadeCoada: "8.3", retornoSessao: "6.8", estoqueFinal: "35", visitantes: "Não informado" },
    { tipoSessao: "Extra", mestreDirigente: "Mestres Darciole", data: "19/05/2024", participantes: "15", quemExplanou: "Não informado", quemLeuDocumentos: "Não informado", estoqueInicial: "35.8", quantidadeCoada: "5.3", retornoSessao: "2", estoqueFinal: "33.8", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "Aujor", data: "01/06/2024", participantes: "42", quemExplanou: "Mariane", quemLeuDocumentos: "Kaua (Dav imbaù)", estoqueInicial: "33.8", quantidadeCoada: "6.000", retornoSessao: "5.1", estoqueFinal: "28.7", visitantes: "Não informado" },
    { tipoSessao: "Instrutiva", mestreDirigente: "Mestre Davi", data: "02/06/2024", participantes: "19", quemExplanou: "Não informado", quemLeuDocumentos: "Não informado", estoqueInicial: "28", quantidadeCoada: "3.300", retornoSessao: "1.800", estoqueFinal: "26.2", visitantes: "Não informado" },
    { tipoSessao: "Concurso", mestreDirigente: "CDC Gilnei", data: "18/06/2024", participantes: "47", quemExplanou: "Vianei", quemLeuDocumentos: "Pablo Tenente", estoqueInicial: "26.2", quantidadeCoada: "6.3", retornoSessao: "5.3", estoqueFinal: "21", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "Mestre Michel", data: "07/07/2024", participantes: "52", quemExplanou: "Cdc Rafael", quemLeuDocumentos: "Vianei", estoqueInicial: "16.1", quantidadeCoada: "6.6", retornoSessao: "6.1", estoqueFinal: "10.0", visitantes: "Não informado" },
    { tipoSessao: "Adventicios", mestreDirigente: "Mestre David Degraf", data: "19/07/2024", participantes: "20", quemExplanou: "Diego de Jezus", quemLeuDocumentos: "Julyano Javorski", estoqueInicial: "Não informado", quantidadeCoada: "3300", retornoSessao: "3200", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Adventicios", mestreDirigente: "Mestre David Degraf", data: "19/07/2024", participantes: "25", quemExplanou: "Diego de Jezus", quemLeuDocumentos: "Juliano Javorski", estoqueInicial: "Não informado", quantidadeCoada: "3800", retornoSessao: "3200", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala Anual", mestreDirigente: "Mestre David Degraf", data: "22/07/2024", participantes: "47", quemExplanou: "Conselheiro Gustavo Gealh", quemLeuDocumentos: "Diego de Jezus", estoqueInicial: "Não informado", quantidadeCoada: "7.1", retornoSessao: "5.0", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Extra", mestreDirigente: "Mestre Roberto Souto Maior", data: "26/07/2024", participantes: "80", quemExplanou: "Não informado", quemLeuDocumentos: "Não informado", estoqueInicial: "Não informado", quantidadeCoada: "12.6", retornoSessao: "9.0", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "Conselheiro Gustavo", data: "17/08/2024", participantes: "52", quemExplanou: "Irmã Heloisa Murback", quemLeuDocumentos: "Irmã Mariana Prado", estoqueInicial: "Não informado", quantidadeCoada: "7.0", retornoSessao: "5.5", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Instrutiva", mestreDirigente: "Mestre Davi", data: "06/09/2024", participantes: "27", quemExplanou: "Não informado", quemLeuDocumentos: "Não informado", estoqueInicial: "Não informado", quantidadeCoada: "2.5", retornoSessao: "2.1", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "Irmã Eloisa Murbach", data: "07/09/2024", participantes: "47", quemExplanou: "Irmão Aujor", quemLeuDocumentos: "Irmã Ana Paula", estoqueInicial: "Não informado", quantidadeCoada: "6.5", retornoSessao: "4.0", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "Mestre Cassio", data: "19/10/2024", participantes: "50", quemExplanou: "Irmao Reinald", quemLeuDocumentos: "Irma Brenda", estoqueInicial: "13.0", quantidadeCoada: "9.0", retornoSessao: "6.0", estoqueFinal: "7.0", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "Mestre João Bosco", data: "16/11/2024", participantes: "50", quemExplanou: "Irmao Pietro", quemLeuDocumentos: "Irmã Iona", estoqueInicial: "100.6", quantidadeCoada: "6.5", retornoSessao: "4.5", estoqueFinal: "96.1", visitantes: "Irmão Iedo, Mestre João Bosco, Mestre Irlan" },
    { tipoSessao: "Instrutiva", mestreDirigente: "Mestre Cassio", data: "03/11/2024", participantes: "25", quemExplanou: "Não informado", quemLeuDocumentos: "Não informado", estoqueInicial: "Não informado", quantidadeCoada: "3.2", retornoSessao: "2.2", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Extra", mestreDirigente: "Conselheiro Gustavo Gealh", data: "23/11/2024", participantes: "11", quemExplanou: "Não informado", quemLeuDocumentos: "Não informado", estoqueInicial: "Não informado", quantidadeCoada: "3.3", retornoSessao: "2.0", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "Mestre Irlan - Mestre Cassio", data: "07/12/2024", participantes: "44", quemExplanou: "irmão Pablo Almeida", quemLeuDocumentos: "irmão Reinald Mendes", estoqueInicial: "Não informado", quantidadeCoada: "8.5", retornoSessao: "6.8", estoqueFinal: "Não informado", visitantes: "Mestre Irlan, Conselheira Lucia" },
    { tipoSessao: "Escala Anual", mestreDirigente: "Mestre Cassio", data: "24/12/2024", participantes: "50", quemExplanou: "Não informado", quemLeuDocumentos: "Não informado", estoqueInicial: "Não informado", quantidadeCoada: "9.0", retornoSessao: "5.3", estoqueFinal: "Não informado", visitantes: "Lucas Cássio, Fabiano De Pádua, Roberta Cássio, Luan Cássio, José Cássio Da Silva Junior, Eduarda Flores, Christian, Flávia e familiares, Ines Zittlau." },
    { tipoSessao: "Escala", mestreDirigente: "Mestre Alessio", data: "04/01/2025", participantes: "65", quemExplanou: "Conselheiros Vinícius", quemLeuDocumentos: "Irmao Fernando", estoqueInicial: "Não informado", quantidadeCoada: "12.5", retornoSessao: "8.5", estoqueFinal: "Não informado", visitantes: "C. Inês, Otto, Mestre Alessio, C. Sônia, Fernando, Dominique, C. Roberto, C. Fabiano, Mestre Robert, C. Kelly, Arthur, Luiza, C. Vinícius, Michele, Marilize, Everton, Raquel" },
    { tipoSessao: "Escala Anual", mestreDirigente: "Mestre Leonardo Bassani", data: "06/01/2025", participantes: "40", quemExplanou: "Irmao Juliano", quemLeuDocumentos: "Irmao Carlos Eduardo", estoqueInicial: "Não informado", quantidadeCoada: "4.0", retornoSessao: "3.4", estoqueFinal: "Não informado", visitantes: "Irmao Carlos Henrique, Mestre Leonardo Bassani, Conselheiro Aguilaine Bassani" },
    { tipoSessao: "Escala", mestreDirigente: "Mestre Cassio", data: "18/01/2025", participantes: "42", quemExplanou: "Irmao Gregor", quemLeuDocumentos: "Irmã Renata", estoqueInicial: "Não informado", quantidadeCoada: "6.0", retornoSessao: "3.5", estoqueFinal: "Não informado", visitantes: "Irmao Carlos Henrique, Irmã Wenndy Hayssa, Irmão Gregor Ipojucan, Irmã Renata Helena Vasque" },
    { tipoSessao: "Escala", mestreDirigente: "CDC Lúcia", data: "01/02/2025", participantes: "50", quemExplanou: "João Pedro", quemLeuDocumentos: "Allanys", estoqueInicial: "Não informado", quantidadeCoada: "3.6", retornoSessao: "3.5", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Instrutiva", mestreDirigente: "Irland", data: "09/02/2025", participantes: "21", quemExplanou: "Não informado", quemLeuDocumentos: "Não informado", estoqueInicial: "Não informado", quantidadeCoada: "3.2", retornoSessao: "3.1", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala Anual", mestreDirigente: "Mestre Cassio", data: "02/10/2025", participantes: "50", quemExplanou: "Carlos Henrique", quemLeuDocumentos: "Brenda", estoqueInicial: "Não informado", quantidadeCoada: "6.5", retornoSessao: "6.1", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala Anual", mestreDirigente: "Mestre Cassio", data: "21/02/2025", participantes: "40", quemExplanou: "Conselheiro Gilnei", quemLeuDocumentos: "Irmão Juliano", estoqueInicial: "Não informado", quantidadeCoada: "5.0", retornoSessao: "3.8", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "Irmão Cristiano Gatelli", data: "03/04/2025", participantes: "22", quemExplanou: "Não informado", quemLeuDocumentos: "Não informado", estoqueInicial: "Não informado", quantidadeCoada: "2.8", retornoSessao: "2.5", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "Mestre Cassio", data: "15/03/2025", participantes: "49", quemExplanou: "Irmã Fernanda", quemLeuDocumentos: "Irmão Vianei", estoqueInicial: "Não informado", quantidadeCoada: "6.0", retornoSessao: "5.0", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "Mestre Clayton", data: "27/03/2025", participantes: "57", quemExplanou: "CDC José", quemLeuDocumentos: "Admilson Anhaia", estoqueInicial: "8.0", quantidadeCoada: "8.0", retornoSessao: "5.3", estoqueFinal: "2.7", visitantes: "Clayton Sacramento de Jesus Gomes, Cons José Massuqueti, Eloisa Murbach" },
    { tipoSessao: "Escala", mestreDirigente: "Mestre Cássio", data: "04/04/2025", participantes: "38", quemExplanou: "Não informado", quemLeuDocumentos: "Não informado", estoqueInicial: "4700", quantidadeCoada: "4700", retornoSessao: "3500", estoqueFinal: "1200", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "Mestre Irland", data: "04/05/2025", participantes: "53", quemExplanou: "Ir. Pablo", quemLeuDocumentos: "Ir. Catarina", estoqueInicial: "7700", quantidadeCoada: "7700", retornoSessao: "4450", estoqueFinal: "3250", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "Juliano", data: "12/04/2025", participantes: "28", quemExplanou: "Não informado", quemLeuDocumentos: "Não informado", estoqueInicial: "4.0", quantidadeCoada: "4.0", retornoSessao: "2.250", estoqueFinal: "1.750", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "Jose Eduardo", data: "19/04/2025", participantes: "54", quemExplanou: "Jocineide", quemLeuDocumentos: "Franciele", estoqueInicial: "7.0", quantidadeCoada: "7.0", retornoSessao: "4.2", estoqueFinal: "4.2", visitantes: "M.jose Eduardo, C.cristina, Irmao Guilherme, Irmao Diego, Irmã Franciele" },
    { tipoSessao: "Escala", mestreDirigente: "Jose Eduardo", data: "21/04/2025", participantes: "95", quemExplanou: "C.pietro", quemLeuDocumentos: "Irmao Aujor", estoqueInicial: "12.0", quantidadeCoada: "12.0", retornoSessao: "4.9", estoqueFinal: "4.9", visitantes: "25" },
    { tipoSessao: "Escala", mestreDirigente: "Gabriel Conde", data: "03/05/2025", participantes: "48", quemExplanou: "Humberto", quemLeuDocumentos: "Simone", estoqueInicial: "4.0", quantidadeCoada: "4.0", retornoSessao: "2.1", estoqueFinal: "2.1", visitantes: "2" },
    { tipoSessao: "Escala", mestreDirigente: "Mestre Gabriel Condé", data: "04/05/2025", participantes: "26", quemExplanou: "Não informado", quemLeuDocumentos: "Não informado", estoqueInicial: "4100", quantidadeCoada: "4100", retornoSessao: "2400", estoqueFinal: "1700", visitantes: "Mestre Gabriel Condé, CDC Humberto" },
    { tipoSessao: "Escala", mestreDirigente: "Mestre Irland", data: "18/04/2025", participantes: "14", quemExplanou: "Não informado", quemLeuDocumentos: "Não informado", estoqueInicial: "Não informado", quantidadeCoada: "5.0", retornoSessao: "1.0", estoqueFinal: "Não informado", visitantes: "Não informado" },
    { tipoSessao: "Escala", mestreDirigente: "CI Patrícia", data: "10/05/2025", participantes: "47", quemExplanou: "Não informado", quemLeuDocumentos: "Não informado", estoqueInicial: "5300", quantidadeCoada: "5300", retornoSessao: "2800", estoqueFinal: "2500", visitantes: "Não" },
    { tipoSessao: "Escala", mestreDirigente: "CDC Jacqueline", data: "17/05/2025", participantes: "50", quemExplanou: "CDC Ema", quemLeuDocumentos: "Não informado", estoqueInicial: "Não informado", quantidadeCoada: "0", retornoSessao: "0", estoqueFinal: "0", visitantes: "Não informado" }
];

// Função principal de seed
const seedDB = async () => {
    try {
        await mongoose.connect(MONGO_URI);
        console.log('Conexão com o MongoDB estabelecida!');

        // Limpa a coleção antes de popular
        await Sessao.deleteMany({});
        console.log('Coleção de sessões limpa.');

        const sessoesParaInserir = dadosBrutos.map(sessaoBruta => {
            // 1. Converte e limpa os dados
            const quantidadeCoada = parseFloat(String(sessaoBruta.quantidadeCoada).replace(',', '.')) || 0;
            const retornoSessao = parseFloat(String(sessaoBruta.retornoSessao).replace(',', '.')) || 0;
            const estoqueInicial = parseFloat(String(sessaoBruta.estoqueInicial).replace(',', '.')) || 0;
            const estoqueFinalExistente = parseFloat(String(sessaoBruta.estoqueFinal).replace(',', '.')) || 0;
            const participantes = parseInt(sessaoBruta.participantes) || 0;
            
            const tipoSessaoEnum = ["Escala", "Escala Anual", "Instrutiva", "Quadro de Mestres", "Direção", "Extra", "Adventícios", "Outros"];
            let tipoSessao = tipoSessaoEnum.includes(sessaoBruta.tipoSessao) ? sessaoBruta.tipoSessao : 'Outros';

            // 2. Calcula os campos obrigatórios
            const quantidadeBebida = quantidadeCoada - retornoSessao;
            const estoqueFinal = estoqueFinalExistente > 0 ? estoqueFinalExistente : (estoqueInicial + quantidadeCoada) - quantidadeBebida;
            const visitante = sessaoBruta.visitantes && sessaoBruta.visitantes !== "Não informado" && sessaoBruta.visitantes !== "Não" ? sessaoBruta.visitantes : "";

            // 3. Formata a data
            const [dia, mes, ano] = sessaoBruta.data.split('/');
            const dataFormatada = new Date(`${ano}-${mes}-${dia}T00:00:00Z`);

            return {
                ...sessaoBruta,
                tipoSessao: tipoSessao,
                participantes: participantes,
                quemExplanou: (sessaoBruta.quemExplanou === "Não informado" || sessaoBruta.quemExplanou === "Sem") ? "" : sessaoBruta.quemExplanou,
                quemLeuDocumentos: (sessaoBruta.quemLeuDocumentos === "Não informado" || sessaoBruta.quemLeuDocumentos === "Sem") ? "" : sessaoBruta.quemLeuDocumentos,
                visitante: visitante,
                vegetal: "Não informado", // Adiciona o campo obrigatório `vegetal`
                quantidadeBebida: quantidadeBebida,
                estoqueInicial: estoqueInicial,
                quantidadeCoada: quantidadeCoada,
                retornoSessao: retornoSessao,
                estoqueFinal: estoqueFinal,
                dataSessao: dataFormatada,
                chamadasFeitas: "", // Campo não informado, pode ser uma string vazia
                mestreDirigente: sessaoBruta.mestreDirigente || "",
            };
        });

        const result = await Sessao.insertMany(sessoesParaInserir);
        console.log(`Dados inseridos com sucesso: ${result.length} documentos.`);

    } catch (error) {
        console.error('Erro ao popular a base de dados:', error);
    } finally {
        await mongoose.connection.close();
        console.log('Conexão com o MongoDB fechada.');
    }
};

seedDB();